# Generated by Django 2.0.7 on 2019-02-10 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='merchant trade_no')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='alipay trade_no')),
                ('pay_status', models.CharField(default='wait_for_pay', max_length=30, verbose_name='pay_status')),
                ('order_amount', models.FloatField(default=0.0, verbose_name='order_amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='pay_time')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_game_id', models.IntegerField(default=0, verbose_name='fav_game_id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='addtime')),
            ],
            options={
                'verbose_name': 'userfav',
                'verbose_name_plural': 'userfav',
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Game2', verbose_name='game')),
            ],
            options={
                'verbose_name': 'usergame',
                'verbose_name_plural': 'usergame',
            },
        ),
    ]
