# Generated by Django 2.0.7 on 2018-11-05 16:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20181016_0010'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='order_sn')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='trade_no')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'closed'), ('WAIT_BUYER_PAY', 'wait_for_pay'), ('TRADE_FINISHED', 'trade_finished')], default='paying', max_length=30, verbose_name='pay_status')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='order_amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='pay_time')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Game', verbose_name='game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
            },
        ),
    ]
