# Generated by Django 2.0.7 on 2018-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='merchant trade_no'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', 'success'), ('TRADE_CLOSED', 'closed'), ('WAIT_BUYER_PAY', 'wait_for_pay'), ('TRADE_FINISHED', 'trade_finished')], default='wait_for_pay', max_length=30, verbose_name='pay_status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='alipay trade_no'),
        ),
    ]
