# Generated by Django 2.0.7 on 2018-11-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20181113_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_sn',
        ),
    ]
