# Generated by Django 2.0.7 on 2018-11-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_remove_order_order_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_mount',
            new_name='order_amount',
        ),
    ]
