# Generated by Django 2.0.7 on 2018-11-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20181114_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(default='wait_for_pay', max_length=30, verbose_name='pay_status'),
        ),
    ]
