# Generated by Django 2.0.7 on 2018-10-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserInfo', 'verbose_name_plural': 'UserInfo'},
        ),
    ]
