# Generated by Django 2.0.7 on 2019-02-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecompany',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='gamecompany',
            name='game_nums',
        ),
        migrations.RemoveField(
            model_name='gamecompany',
            name='image',
        ),
    ]
