"""
Django settings for GameShop project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(y)m@6t3g8&c&k+%53dinvxyr4qh)0h57ek8p3-efb5l#4q)z1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'company',
    'operation',
    'game'

]
AUTH_USER_MODEL = 'users.UserProfile'

AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GameShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'GameShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "GameShop",
        'USER': "root",
        'PASSWORD': "ssjusher123",
        'HOST': "127.0.0.1",
        'OPTIONS': {
                'charset': 'utf8mb4',
            }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


STATIC_URL = '/static/'
# STATIC_ROOT = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

#支付宝相关配置
private_key_path = os.path.join(BASE_DIR, 'apps/utils/private_2048.txt')
ali_pub_key_path = os.path.join(BASE_DIR, 'apps/utils/alipay_key.txt')
steam_data_action = os.path.join(BASE_DIR, "apps/utils/steam_data_action")
steam_data_adventure = os.path.join(BASE_DIR, "apps/utils/steam_data_adventure")
steam_data_independent = os.path.join(BASE_DIR, "apps/utils/steam_data_independent")
steam_data_leisure = os.path.join(BASE_DIR, "apps/utils/steam_data_leisure")
steam_data_moba = os.path.join(BASE_DIR, "apps/utils/steam_data_moba")
steam_data_racing = os.path.join(BASE_DIR, "apps/utils/steam_data_racing")
steam_data_role_play = os.path.join(BASE_DIR, "apps/utils/steam_data_roleplay")
steam_data_simulation = os.path.join(BASE_DIR, "apps/utils/steam_data_simulation")
steam_data_sports = os.path.join(BASE_DIR, "apps/utils/steam_data_sports")
steam_data_strategy = os.path.join(BASE_DIR, "apps/utils/steam_data_strategy")


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "a965769897@gmail.com"
EMAIL_HOST_PASSWORD = "a965769897"
EMAIL_USE_TLS = True
EMAIL_FROM = "a965769897@gmail.com"
