# Generated by Django 2.0.7 on 2018-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(upload_to='game/%Y/%m', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_1',
            field=models.ImageField(upload_to='game/%Y/%m', verbose_name='gameimage1'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_2',
            field=models.ImageField(upload_to='game/%Y/%m', verbose_name='gameimage2'),
        ),
    ]
